package com.cts.teacher.domain;
// Generated 2016-11-29 1:16:02 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.cts.teacher.enumtype.SysStatusEnum;
import com.cts.teacher.jsontype.QuestionSnapshotJsonType;

/**
 * CtsTeacherExamPaper generated by hbm2java
 */
@Entity
@Table(name = "cts_teacher_exam_paper", catalog = "chinats")
public class CtsTeacherExamPaper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8374769537668475938L;
	private Long id;
	private Integer createTime;
	private Integer updateTime;
	private Long createUser;
	private Long updateUser;
	private SysStatusEnum sysStatus;
	private Long teacherId;
	private QuestionSnapshotJsonType questionsSnapshot;
	private String answerResult;
	private Integer finalMark;

	public CtsTeacherExamPaper() {
	}

	public CtsTeacherExamPaper(Integer createTime, Integer updateTime, Long createUser, Long updateUser, SysStatusEnum sysStatus,
			Long teacherId, QuestionSnapshotJsonType questionsSnapshot, String answerResult, Integer finalMark) {
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.sysStatus = sysStatus;
		this.teacherId = teacherId;
		this.questionsSnapshot = questionsSnapshot;
		this.answerResult = answerResult;
		this.finalMark = finalMark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "create_time")
	public Integer getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_time")
	public Integer getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "create_user")
	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	@Column(name = "update_user")
	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "sys_status")
	@Enumerated(EnumType.ORDINAL)
	public SysStatusEnum getSysStatus() {
		return this.sysStatus;
	}

	public void setSysStatus(SysStatusEnum sysStatus) {
		this.sysStatus = sysStatus;
	}

	@Column(name = "teacher_id")
	public Long getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Long teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "questions_snapshot")
	public QuestionSnapshotJsonType getQuestionsSnapshot() {
		return this.questionsSnapshot;
	}

	public void setQuestionsSnapshot(QuestionSnapshotJsonType questionsSnapshot) {
		this.questionsSnapshot = questionsSnapshot;
	}

	@Column(name = "answer_result")
	public String getAnswerResult() {
		return this.answerResult;
	}

	public void setAnswerResult(String answerResult) {
		this.answerResult = answerResult;
	}

	@Column(name = "final_mark")
	public Integer getFinalMark() {
		return this.finalMark;
	}

	public void setFinalMark(Integer finalMark) {
		this.finalMark = finalMark;
	}

}
