package com.cts.teacher.domain.dto;
// Generated 2016-11-29 1:16:02 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.cts.common.enumtype.SysStatusEnum;
import com.cts.sys.entity.BaseDO;

/**
 * CtsTeacherExamQuestion generated by hbm2java
 */
@Entity
@Table(name = "cts_teacher_exam_question")
public class CtsTeacherExamQuestionDO extends BaseDO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6470136728952707850L;
	private Long id;
	private Long createTime;
	private Long updateTime;
	private Long createUser;
	private Long updateUser;
	private SysStatusEnum sysStatus;
	private String title;
	private String content;
	private Integer questionValue;

	public CtsTeacherExamQuestionDO() {
	}

	public CtsTeacherExamQuestionDO(Long createTime, Long updateTime, Long createUser, Long updateUser,
			SysStatusEnum sysStatus, String title, String content, Integer questionValue) {
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.sysStatus = sysStatus;
		this.title = title;
		this.content = content;
		this.questionValue = questionValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_time")
	public Long getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "create_user")
	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	@Column(name = "update_user")
	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "sys_status")
	@Enumerated(EnumType.ORDINAL)
	public SysStatusEnum getSysStatus() {
		return this.sysStatus;
	}

	public void setSysStatus(SysStatusEnum sysStatus) {
		this.sysStatus = sysStatus;
	}

	@Column(name = "title", length = 253)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 4096)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "question_value")
	public Integer getQuestionValue() {
		return this.questionValue;
	}

	public void setQuestionValue(Integer questionValue) {
		this.questionValue = questionValue;
	}

}
