package com.cts.teacher.domain.dto;
// Generated 2016-11-29 1:16:02 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.cts.common.enumtype.SysStatusEnum;
import com.cts.sys.entity.BaseDO;

/**
 * CtsUserTeacher generated by hbm2java
 */
@Entity
@Table(name = "cts_user_teacher")
public class CtsUserTeacherDO extends BaseDO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 866386156944490456L;
	private Long id;
	private Long createTime;
	private Long createUser;
	private Long updateUser;
	private Long updateTime;
	private SysStatusEnum sysStatus;
	private String firstName;
	private String lastName;

	public CtsUserTeacherDO() {
	}

	public CtsUserTeacherDO(Long createTime, Long createUser, Long updateUser, Long updateTime,
			SysStatusEnum sysStatus, String firstName, String lastName) {
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.sysStatus = sysStatus;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "create_time", updatable = false)
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "create_user", updatable = false)
	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	@Column(name = "update_user")
	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "update_time")
	public Long getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "sys_status")
	@Enumerated(EnumType.ORDINAL)
	public SysStatusEnum getSysStatus() {
		return this.sysStatus;
	}

	public void setSysStatus(SysStatusEnum sysStatus) {
		this.sysStatus = sysStatus;
	}

	@Column(name = "first_name", length = 256)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 256)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Override
	public String toString() {
		return "CtsUserTeacher [id=" + id + ", createTime=" + createTime + ", createUser=" + createUser
				+ ", updateUser=" + updateUser + ", updateTime=" + updateTime + ", sysStatus=" + sysStatus
				+ ", firstName=" + firstName + ", lastName=" + lastName + "]";
	}

}
